### ISSUE TITLE
如何用labelme根据不同框的起点标注线段

### ISSUE THREAD

**Issue by OBVIOUSDAWN** [DongZhouGu/vcoco_utils#1]
您好，很感谢您提供的转换脚本用于vcoco数据集的标注。在使用中我发现了一个问题，labelme标线段如果手动标注，就无法在关联两个框的x1y1点间建立一条线，手动标会存在误差。结果如下

开源原版
`    {
      "shape_type": "line",
      "points": [
        [
          212.9344262295082,
          82.47540983606558
        ],
        [
          108.01639344262296,
          150.5081967213115
        ]
      ],
      "flags": {},
      "group_id": null,
      "label": "ride_instr"
    }

{
      "shape_type": "rectangle", 
      "points": [
        [
          212.9344262295082, 
          82.47540983606558
        ], 
        [
          320.3114754098361, 
          266.9016393442623
        ]
      ], 
      "flags": {}, 
      "group_id": null, 
      "label": "person"
    },
 {
      "shape_type": "rectangle",
      "points": [
        [
          108.01639344262296,
          150.5081967213115
        ],
        [
          489.9836065573771,
          359.5245901639344
        ]
      ],
      "flags": {},
      "group_id": null,
      "label": "horse"
    },`  
其中线段端点完全和框的端点一样，但我手动标注的就会出现误差

`        {
      "label": "4444",
      "points": [
        [
          1022.5988700564972,
          470.6214689265537
        ],
        [
          1032.2033898305085,
          852.542372881356
        ]
      ],
      "group_id": null,
      "shape_type": "line",
      "flags": {}
    },
{
      "label": "111",
      "points": [
        [
          1022.8070175438595,
          471.61403508771923
        ],
        [
          1635.9649122807016,
          1075.9999999999998
        ]
      ],
      "group_id": null,
      "shape_type": "rectangle",
      "flags": {}
    },
    {
      "label": "222",
      "points": [
        [
          1031.578947368421,
          852.3157894736842
        ],
        [
          1297.3684210526314,
          1047.0526315789473
        ]
      ],
      "group_id": null,
      "shape_type": "rectangle",
      "flags": {}
    },
`
感激不尽

**Comment by DongZhouGu** [comment]
很高兴能帮到你
手动标注确实存在误差，无法避免
所以在转换代码中有处理这个误差的逻辑：对于"shape_type": "line",找到距离两个端点最近的两个"shape_type": "rectangle",
[trans_json.py-line33](https://github.com/DongZhouGu/vcoco_utils/blob/master/trans_json.py) 
```
for shape in anno['shapes']:
        if shape['shape_type'] == 'line':
            person_point = shape['points'][0]
            role_point = shape['points'][1]
            min_person_dis = 1000
            min_role_dis = 1000
            for i, obj in enumerate(valid_objs):
                person_distance = dis(person_point, obj[:2])
                role_distance = dis(role_point, obj[:2])
                if person_distance < min_person_dis:
                    person_id = i
                    min_person_dis = person_distance
                if role_distance < min_role_dis:
                    role_id = i
                    min_role_dis = role_distance

            assert valid_objs[person_id][-1] == 'person', '{}.json文件标注错误'.format(file_id)
            assert valid_objs[role_id][-1] != 'person', '{}.json文件标注错误'.format(file_id)
            valid_action.append([person_id, role_id, shape['label']])
```

**Comment by OBVIOUSDAWN** [comment]
感激不尽，我之前一直不知道怎么标注hoi格式，基本靠手动输入加部分脚本转换，标注错误率一直太高，很感谢您的代码提供了一种精确的标注方式
