### ISSUE TITLE
trans_json.py处理后生成的json文件相关问题

### ISSUE THREAD

**Issue by OBVIOUSDAWN** [DongZhouGu/vcoco_utils#2]
实在抱歉又打扰了，我尝试使用脚本处理了标注，生成了我自己的dataset.json。但我不知道它是否是替代原版vcoco[https://github.com/s-gupta/v-coco/tree/master/data/vcoco](url)中这个部分的，原版vcoco包含了四个json，但它们的格式和生成的json有明显不同，我不知道生成的json该如何使用。另外我想知道您的111.json是用那种hoi检测模型检测生成的，感激不尽。
不知道大佬现在还在做hoi相关的内容吗？希望能和大佬加个qq进行请教学习，万分感谢

**Comment by DongZhouGu** [comment]
Wechat: Madon678
